# Setup
title:            Frederico Zveiter
description:      'Game Developer'
url:              http://fredzvt.github.io
baseurl:          /

author:
  name:           'Frederico Zveiter'
  url:            https://www.linkedin.com/in/fredericozveiter
  
# Dependencies
markdown:         redcarpet
highlighter:      pygments